name: Deployment to Production

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://cicd.ap-northeast-2.elasticbeanstalk.com
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup Go environment
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: ${{ secrets.BEANSTALK_ENV_NAME }}
          version_label: 12345
          region: ap-northeast-2
          deployment_package: deploy.zip

# soomgo 로직
#       - name: Build Application
#         run: |
#           node -v
#           npm install
#           npm run build
#           ls -la
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-northeast-2
#       - name: Deploy to EB
#         run: |
#           git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
#           ./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer
#           echo 'export PATH="/home/runner/.ebcli-virtual-env/executables:$PATH"' >> ~/.bash_profile && source ~/.bash_profile
#           eb init ${{ secrets.APPLICATION_NAME }} -r ap-northeast-2 -p "node.js"
#           eb deploy ${{ secrets.BEANSTALK_ENV_NAME }} --debug -v --staged
