name: Deployment to Production

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://cicd.ap-northeast-2.elasticbeanstalk.com
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup Go environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
      - name: Build Application
        run: |
          node -v
          npm install
          npm run build
          ls -la
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: ${{ secrets.BEANSTALK_ENV_NAME }}
          version_label: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          region: ap-northeast-2
          deployment_package: deploy.zip
